apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: color-web
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: color-web
      previewService: color-web-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: color-web
  template:
    metadata:
      labels:
        app: color-web
    spec:
      containers:
      - name: color-web
        image: preethyvenkat1122/color-webapp:v5
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "#28A745"  # green
          #value: "#007BFF" # blue
