---
apiVersion: v1
kind: Service
metadata:
 name: color-web-active
spec:
 selector:
   app: color-web
   version: blue   # matches initial Rollout pod labels
 ports:
   - port: 80
     targetPort: 8081
 type: NodePort
---
apiVersion: v1
kind: Service
metadata:
 name: color-web-preview
spec:
 selector:
   app: color-web
   version: green  # placeholder for future green preview
 ports:
   - port: 80
     targetPort: 8081
 type: NodePort
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
 name: color-web
spec:
 replicas: 1
 strategy:
   blueGreen:
     activeService: color-web-active
     previewService: color-web-preview
     autoPromotionEnabled: false
     # Analysis will be applied only when green preview pods exist
     prePromotionAnalysis:
       templates:
         - templateName: preview-pod-health
 selector:
   matchLabels:
     app: color-web
     version: blue   # initial active version
 template:
   metadata:
     labels:
       app: color-web
       version: blue   # initial active version
   spec:
     containers:
       - name: color-web
         image: preethyvenkat1122/color-webapp:v6.1
         ports:
           - containerPort: 8081
         env:
           - name: COLOR
             value: "#0000FF"   # blue
             # value: "#FFFF00" # yellow
             # value: "#28A745" # green
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
 name: preview-pod-health
spec:
 metrics:
   - name: pod-health
     interval: 10s
     count: 3
     successCondition: result == 1
     failureCondition: result != 1
     provider:
       job:
         spec:
           template:
             spec:
               containers:
                 - name: check
                   image: curlimages/curl
                   command: ["/bin/sh", "-c"]
                   args: ["curl -s http://color-web-preview:80 && echo 1 || echo 0"]
               restartPolicy: Never
