apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-web-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-web
      version: blue
  template:
    metadata:
      labels:
        app: color-web
        version: blue
    spec:
      containers:
        - name: color-web
          image: preethyvenkat1122/color-webapp:v3
          ports:
            - containerPort: 8081
          env:
           - name: COLOR
             value: "#007BFF"  # blue        
             #value: "#FFBF00"   # yellow
