apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-web
  template:
    metadata:
      labels:
        app: color-web
    spec:
      containers:
      - name: color-web
        image: 141409473062.dkr.ecr.us-east-1.amazonaws.com/color-webapp:v3
        ports:
        - containerPort: 80
