apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-web
  template:
    metadata:
      labels:
        app: color-web
    spec:
      containers:
      - name: color-web
        image: preethyvenkat1122/color-webapp:v1
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "#FFBF00"
