apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-web
  template:
    metadata:
      labels:
        app: color-web
    spec:
      containers:
      - name: color-web
        image: hashicorp/http-echo
        args:
          - "-text=<html><body style='background-color:#008080'><h1>Hello GitOps!</h1></body></html>"
        ports:
        - containerPort: 5678
