apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: color-cluster
  region: us-east-1

managedNodeGroups:
  - name: spot-nodes
    instanceTypes:
      - t3.medium
      - t3.large
    capacityType: SPOT
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
