apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: color-app-cluster
  region: us-east-1

managedNodeGroups:
  - name: app-node-group
    instanceTypes:
      - t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
