
---
apiVersion: v1
kind: Service
metadata:
 name: color-web-preview
spec:
 selector:
   app: color-web
   version: green   # green preview pods
 ports:
   - port: 80
     targetPort: 8081
 type: NodePort
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
 name: color-web-green
spec:
 replicas: 1
 strategy:
   blueGreen:
     activeService: color-web-active   # still points to blue
     previewService: color-web-preview
     autoPromotionEnabled: false       # manual promotion
 selector:
   matchLabels:
     app: color-web
     version: green
 template:
   metadata:
     labels:
       app: color-web
       version: green
   spec:
     containers:
       - name: color-web
         image: preethyvenkat1122/color-webapp:v7.1
         ports:
           - containerPort: 8081
         env:
           - name: COLOR
             value: "#28A745"  # green