---
apiVersion: v1
kind: Service
metadata:
 name: color-web-preview
spec:
 selector:
   app: color-web
   version: green
 ports:
   - port: 8081
     targetPort: 8081
 type: NodePort
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
 name: color-web
spec:
 replicas: 1
 strategy:
   blueGreen:
     activeService: color-web-active   # currently pointing to blue
     previewService: color-web-preview
     autoPromotionEnabled: false
     prePromotionAnalysis:
       templates:
         - templateName: preview-pod-health
 selector:
   matchLabels:
     app: color-web
     version: green
 template:
   metadata:
     labels:
       app: color-web
       version: green
   spec:
     containers:
       - name: color-web
         image: preethyvenkat1122/color-webapp:v7.1
         ports:
           - containerPort: 8081
         env:
           - name: COLOR
             value: "#28A745"   # green
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
 name: preview-pod-health
spec:
 metrics:
   - name: pod-health
     interval: 10s
     count: 3
     successCondition: result == 1
     failureCondition: result != 1
     provider:
       job:
         spec:
           template:
             spec:
               containers:
                 - name: check
                   image: curlimages/curl
                   command: ["/bin/sh", "-c"]
                   args: ["curl -s http://color-web-preview:8081 && echo 1 || echo 0"]
               restartPolicy: Never