apiVersion: v1
kind: Service
metadata:
  name: color-web
spec:
  type: NodePort
  selector:
    app: color-web
  ports:
    - protocol: TCP
      port: 80           # Cluster-internal port
      targetPort: 80     # Container port
      nodePort: 31555    # External port (must be between 30000–32767)
