
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: color-web
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: color-web-active
      previewService: color-web-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
          - templateName: preview-pod-health
  selector:
    matchLabels:
      app: color-web
      version: green
  template:
    metadata:
      labels:
        app: color-web
        version: green
    spec:
      containers:
        - name: color-web
          image: preethyvenkat1122/color-webapp:v7.1
          ports:
            - containerPort: 8081
          env:
            - name: COLOR
              value: "#28A745" # green
